class WorkerCategories {
  static const Map<String, List<String>> categories = {
    'Drivers': [
      'Car Driver',
      'Taxi Driver',
      'Cab Driver',
      'Auto Rickshaw Driver',
      'E-Rickshaw Driver',
      'Bus Driver',
      'School Bus Driver',
      'Mini Bus Driver',
      'Truck Driver',
      'Lorry Driver',
      'Mini Truck Driver',
      'Pickup Van Driver',
      'Delivery Van Driver',
      'Courier Driver',
      'Bike Delivery Rider',
      'Scooter Delivery Rider',
      'Tractor Driver',
      'Harvester Driver',
      'Thresher Machine Operator',
      'Sprayer Vehicle Driver',
      'Excavator (JCB) Operator',
      'Bulldozer Driver',
      'Crane Operator',
      'Road Roller Driver',
      'Dump Truck Driver',
      'Concrete Mixer Truck Driver',
      'Ambulance Driver',
      'Garbage Truck Driver',
      'Personal Chauffeur',
      'Valet Driver',
      'Tourist Vehicle Driver',
      'Water Tanker Driver',
      'Oil Tanker Driver',
      'Gas Tanker Driver',
      'Refrigerated Truck Driver',
      'Electric Auto Driver',
      'EV Delivery Driver',
      'Boat Driver',
      'Ferry Boat Driver',
      'Motor Boat Driver',
      'Tourist Boat Driver',
    ],
    'Shop Workers': [
      'Grocery Store Worker',
      'Supermarket Worker',
      'Vegetable Shop Worker',
      'Fruit Shop Worker',
      'Bakery Worker',
      'Sweet Shop Worker',
      'Dairy Shop Worker',
      'Tea Shop Worker',
      'Coffee Shop Worker',
      'Juice Shop Worker',
      'Ice Cream Shop Worker',
      'Restaurant Worker',
      'Fast Food Worker',
      'Street Food Worker',
      'Spice Shop Worker',
      'Dry Fruit Shop Worker',
      'Clothing Shop Worker',
      'Boutique Worker',
      'Saree Shop Worker',
      'Tailor Shop Worker',
      'Footwear Shop Worker',
      'Shoe Shop Worker',
      'Bag Shop Worker',
      'Jewellery Shop Worker',
      'Cosmetic Shop Worker',
      'Perfume Shop Worker',
      'Watch Shop Worker',
      'Mobile Shop Worker',
      'Computer Shop Worker',
      'Laptop Shop Worker',
      'Electronics Shop Worker',
      'TV Appliance Shop Worker',
      'Camera Shop Worker',
      'Gaming Shop Worker',
      'Medical Store Worker',
      'Pharmacy Worker',
      'Ayurvedic Shop Worker',
      'Optical Shop Worker',
      'Surgical Equipment Shop Worker',
      'Pet Medical Shop Worker',
      'Book Store Worker',
      'Stationery Shop Worker',
      'Printing Shop Worker',
      'Photocopy Shop Worker',
      'Internet Cafe Worker',
      'Office Supply Shop Worker',
      'Furniture Shop Worker',
      'Mattress Shop Worker',
      'Hardware Shop Worker',
      'Paint Shop Worker',
      'Electrical Shop Worker',
      'Tiles Shop Worker',
      'Sanitary Shop Worker',
      'Kitchen Equipment Shop Worker',
      'Bike Showroom Worker',
      'Car Showroom Worker',
      'Auto Spare Parts Worker',
      'Tyre Shop Worker',
      'Battery Shop Worker',
      'Car Accessories Worker',
      'Barber',
      'Salon Worker',
      'Beauty Parlour Worker',
      'Laundry Worker',
      'Repair Shop Worker',
      'Tailoring Worker',
      'Travel Agency Worker',
      'Photo Studio Worker',
      'Gift Shop Worker',
      'Toy Shop Worker',
      'Flower Shop Worker',
      'Pet Shop Worker',
      'Hobby Shop Worker',
      'Antique Shop Worker',
      'Art Shop Worker',
      'Mall Staff',
      'Hotel Staff',
      'Company Staff',
      'Sales Staff',
      'Goods Handling Staff',
    ],
    'Physical Workers': [
      'Agriculture Labour',
      'Land Preparation Labour',
      'Sowing Labour',
      'Planting Labour',
      'Irrigation Labour',
      'Crop Maintenance Labour',
      'Harvesting Labour',
      'Post Harvest Labour',
      'Livestock Labour',
      'Dairy Labour',
      'Plantation Labour',
      'Agricultural Transport Labour',
      'Farm Helper',
      'Factory Production Worker',
      'Material Handling Worker',
      'Factory Maintenance Worker',
      'Factory Processing Worker',
      'Quality Support Worker',
      'Cleaning Utility Worker',
      'Factory Construction Worker',
      'Transport Dispatch Worker',
      'Loader',
      'Unloader',
      'Goods Carrier',
      'Warehouse Worker',
      'Stock Worker',
      'Packing Worker',
      'Unpacking Worker',
      'Cart Handler',
      'Trolley Handler',
      'House Cleaner',
      'Sweeper',
      'Floor Cleaner',
      'Toilet Cleaner',
      'Garbage Collector',
      'Drain Cleaner',
      'Waste Handling Worker',
      'Electrician Helper',
      'Plumber Helper',
      'Carpenter Helper',
      'AC Technician Helper',
      'General Repair Worker',
      'Mason',
      'Construction Helper',
      'Painter',
      'Tile Worker',
      'Welder Helper',
      'Fabrication Worker',
      'Glass Fitter',
      'POP Helper',
      'Delivery Helper',
      'Goods Vehicle Helper',
      'Parking Assistant',
      'Valet Helper',
      'Handcart Worker',
      'Cook',
      'Chef',
      'Kitchen Helper',
      'Dish Washer',
      'Table Cleaner',
      'Food Runner',
      'Lift Helper',
      'Escalator Helper',
      'Generator Operator Helper',
      'Gardener',
      'Road Cleaner',
      'Parking Cleaner',
      'Stage Setup Worker',
      'Decoration Worker',
      'Banner Installer',
      'Tent Worker',
      'Security Guard',
      'Bouncer',
      'Watchman',
      'Watchwoman',
    ],
  };

  static List<String> get categoryList => categories.keys.toList();

  static List<String> getOccupationsForCategory(String category) {
    final list = categories[category]?.toList() ?? [];
    if (list.isNotEmpty && !list.contains('Others')) {
      list.add('Others');
    }
    return list;
  }
}
